### ISSUE TITLE
新增字段：POST /clubs/activities

### ISSUE THREAD

**Issue by SeinoNana** [EyesCMS/zhishe-cms-doc#21]
### 6.1 申请活动

```
POST /clubs/activities
```

#### Input

| Name           | Type       | Description |
| -------------- | ---------- | ----------- |
| `clubId`       | `int`      | 社团编号    |
| `name`         | `string`   | 活动名称    |
| `title`        | `string`   | 活动标题    |
| `content`      | `string`   | 活动内容    |
| `startDate`    | `datetime` | 开始时间    |
| `endDate`      | `datetime` | 结束时间    |
| `location`     | `string`   | 地点        |
| `imgUrl`     | `string`   | 图片        |
| `accessoryUrl` | `string`   | 附件        |

#### Example

```json
{
  "clubId": 1,
  "name": "act",
  "title": "this is a title",
  "content": "what content",
  "startDate": "2018-04-19",
  "endDate": "2018-04-22",
  "location": "三区",
  "imgUrl": "https://xxx/xxx/a.png"
  "accessoryUrl": "https://xxx/xxx/a.png"
}
```

#### Response

```json
Status: 201 Created
```

**Comment by kylin773** [comment]
已解决
